name: run unit tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout maybe?
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'
    - name: pytest
      run: |
        python -m pip install --upgrade pip pytest
        pytest
